### PR TITLE
Advanced fix of command and pattern substitutions

### PR DESCRIPTION
**Pull request by triadium**
image

### CODE REVIEW

**Comment by soryy708** [comment]
Hello!
Thank you for the pull request.

If I understand correctly, you want `cross-pwd2` to substitute not just the `pwd` keyword but also `${pwd}` case insensitively.
This is an interesting use case. I think that the regular expression can be simplified by using the [`i` flag](https://stackoverflow.com/questions/9655164/regex-ignore-case-sensitivity), and [`character classes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes).
Please refactor the regular expression, and then I will merge your pull request.
Thank you for your time!

**Comment by soryy708** [comment]
1. Why is the negative lookbehind part neccesary? (`(?<!\\)`)
2. The substring `pwd` repeats 4 times. Can the regex be restructured such that it [doesn't repeat itself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) like so?

**Comment by triadium** [comment]
1. Script `cross-pwd2 node $(pwd)/packages/app1/main.js args=\$(pwd)` must expand into the following expression `node /real-current-directory/packages/app1/main.js args=\$(pwd)`  Escaped **\\$(pwd)** not expands. \`pwd\` instead of $(pwd) could be used to replace properly for the case \\\\$(pwd) - not expands but must :-(  (regular expressions are powerless in such cases, more complex processing is needed, but the game is not worth it IMHO)
2. Tree of the 4 cases with different beginning  - the 4 paths. Bad practice to mix up open/close brackets. I can use interpolation for the 4 places. Will it be enough for the accepting pull request? :-)

**Comment by soryy708** [comment]
Thank you for taking the time to explain the reasoning.
I still don't understand why the lookbehind (`(?<!\\)`) is neccesary.
The way I understand it, the procedure should replace all instances of `pwd`, `{pwd}`, `${pwd}`. This appears to be a regular language, so a regular expression should be able to parse it. Am I missing something?
Perhaps it will be easier to understand all the edge cases if you write some unit tests to check the actual returned value of the procedure against the expected one. [mocha](https://www.npmjs.com/package/mocha) or [jest](https://www.npmjs.com/package/jest) are great for this. + if we write unit tests, we protect against regressions in the future.

**Comment by triadium** [comment]
Hello!

I made the refactoring. And tests to show use cases.

**Comment by triadium** [comment]
@soryy708 Do there need any more actions to get the new version from npm registry? Update readme file?

**Comment by soryy708** [comment]
@triadium No. I published it just now. You should be able to get version `1.0.1` by running `npm install`.

**Pull request merged**
